name: Deploy Static Website to S3

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Deploy files to S3
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete

      # Step 4: Set public read ACL for index.html and error.html files
      - name: Apply Public Read ACL to index.html and error.html
        run: |
          aws s3api put-object-acl --bucket ${{ secrets.S3_BUCKET_NAME }} --acl public-read --key index.html
          aws s3api put-object-acl --bucket ${{ secrets.S3_BUCKET_NAME }} --acl public-read --key error.html
